import type { Readable } from 'node:stream';

/**
 * One storage driver: where photo files live (NS-31). Routes and services use only this interface,
 * never a driver, `node:fs` or an S3 client (NS-33). Keys are generated by the server (NS-01).
 */
export interface StorageDriver {
  readonly name: 'nas' | 's3';
  /** Streams `body` to `key`, replacing any file there. Rejects, leaving no partial file at `key`, if `body` errors. */
  put(key: string, body: Readable, meta: { contentType: string; size?: number }): Promise<void>;
  /** Opens `key` for reading. Throws StorageNotFoundError if there is no file at `key`. */
  get(key: string): Promise<Readable>;
  /** Deletes `key`. Succeeds if it is already gone, so a retry is always safe. */
  remove(key: string): Promise<void>;
}
